name: 打包Mac接口文档生成器
on: workflow_dispatch
# 解决Node版本兼容警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v5
      - name: 配置Python环境
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 打包Mac GUI应用
        run: |
          rm -rf build dist
          # 打包无终端黑框的Mac桌面应用
          pyinstaller --windowed --noconsole --name 接口文档生成器 createDocuments.py
      - name: 上传打包好的App
        uses: actions/upload-artifact@v4
        with:
          name: Mac打包成品
          path: dist/接口文档生成器.app
